version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:current-22.04
    resource_class: medium
    steps:
      - checkout
      - run: 
          name: meet requirement
          command: |
            echo "I'm here"
  test:
    type: no-op 

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build